console.log('Freddy Guo')
console.log('My favorite color is blue.')
console.log('My favorite song is Glorious.')
console.log('My favorite tv program is the NBA.')
console.log('My favorite food is pizza.')
